### ISSUE TITLE
[v5.0.0-beta.2] Calendar is not updated if using eventContent render hook

### ISSUE THREAD

**Issue by phamvuau** [fullcalendar/fullcalendar-react#59] opened 2020-04-15 11:00 UTC
Please check [this example](https://codesandbox.io/s/priceless-elgamal-mpp97?file=/src/App.js)
The event positions were incorrect at the first render.

<img width="729" alt="Screen Shot 2020-04-15 at 6 01 30 PM" src="https://user-images.githubusercontent.com/259848/79330147-3cee2d80-7f43-11ea-97e9-88d8a7f86114.png">

**Comment by leesh22** [comment] 2020-05-20 17:49
Also having this issue with the resourceTimelinePlugin. The calendar cells are not adjusting to the event size on the first render.

**Comment by leesh22** [comment] 2020-05-20 17:56
@phamvuau this thread might be useful to you - https://github.com/fullcalendar/fullcalendar-react/issues/12

**Comment by phamvuau** [comment] 2020-05-21 09:35
@leesh22 yeah this issue is fixed in `v5.0.0-beta.3`

It's weird that my example is broken when clicking RERENDER because there is no `render` method in the calendarApi

<img width="554" alt="Screen Shot 2020-05-21 at 4 31 57 PM" src="https://user-images.githubusercontent.com/259848/82545384-d206c680-9b80-11ea-9b70-5beac3cbd919.png">

**Comment by acerix** [comment] 2020-05-28 20:38
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

Thanks for the report, I will close this since I can confirm it's fixed in beta 3.  I will open an issue about `render` not working as that seems like a bug.

**Closed by acerix** 2020-05-28 20:38 UTC
