### ISSUE TITLE
Plugins Prop not working

### ISSUE THREAD

**Issue by bigjoevtrj** [fullcalendar/fullcalendar-react#20] opened 2019-05-29 19:07 UTC
Error: The FullCalendar view "dayGridMonth" does not exist. Make sure your plugins are loaded correctly.

```
import React from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import '@fullcalendar/core/main.css';
import '@fullcalendar/daygrid/main.css';

const Calendar = props => {
    return <FullCalendar defaultView="dayGridMonth" plugins={ [dayGridPlugin] } />;
};

export default Calendar;
```

**Comment by joshuaRuff** [comment] 2019-06-04 22:32
Would you be able to post a [runnable, stripped-down demonstration of the bug](https://fullcalendar.io/reduced-test-cases)? Would really appreciate it because the time saved reproducing will be time spent fixing.

Also what does your package.json look like? Did you install the dayGridPlugin package?

**Comment by piskunovim** [comment] 2019-06-11 14:29
Hi, @joshuaRuff ! I have the same issue and prepared project to demonstrate it: 
[fullcalendar-daygrid-issue.zip](https://github.com/fullcalendar/fullcalendar-react/files/3276962/fullcalendar-daygrid-issue.zip)
It has no view options to select and other plugins are not active as well. It seems like something missed.

`npm install` && `npm start` commands should run my project.

**Comment by piskunovim** [comment] 2019-06-11 15:30
Okay, I found my issue. I missed [header docs](https://fullcalendar.io/docs/header) part. 
bigjoevtrj, hope this will help you.
 
`<FullCalendar defaultView="dayGridWeek" header={{ left: 'prev,next', center: 'title', right: 'dayGridDay,dayGridWeek' }} plugins={[dayGridPlugin]}/>`

**Comment by bigjoevtrj** [comment] 2019-06-11 16:04
I'll give it a try this week, I'm working on another project right now.

But with me Component doesn't work but pure FullCalendar library yes.

If header prop is requiried to this Component be able to work doesn't it should be marked as required in PropTypes?

**Comment by piskunovim** [comment] 2019-06-11 16:53
@bigjoevtrj please, ignore my previous message. I thought that you cannot see different views. Anyway, I've prepared basic example based on your code. Could you try it on your side?  
[fullcalendar-basic-example.zip](https://github.com/fullcalendar/fullcalendar-react/files/3277608/fullcalendar-basic-example.zip)
`npm install` && `npm start` should be enough to start it.

**Comment by ashvin777** [comment] 2020-09-03 12:59
I was able to solve this by using the same version for all plugins. I was using a different versions by mistake which was leading to this issue. Using the same version for `@fullcalendar` npm modules will resolve this problem. 

Like below -
```
    "@fullcalendar/daygrid": "5.1.0",
    "@fullcalendar/interaction": "5.1.0",
    "@fullcalendar/moment-timezone": "5.3.0",
    "@fullcalendar/react": "5.1.0",
    "@fullcalendar/timegrid": "5.1.0",
```

**Comment by trung3t123** [comment] 2021-06-14 11:19
@ashvin777 its works, thankss

**Comment by RoniqueRicketts** [comment] 2021-07-07 01:42
I am experiencing this same issue.  I have the following
```
"@fullcalendar/core": "^5.8.0",
    "@fullcalendar/daygrid": "^5.8.0",
    "@fullcalendar/interaction": "^5.8.0",
    "@fullcalendar/moment": "^5.8.0",
    "@fullcalendar/react": "^5.8.0",
    "@fullcalendar/timegrid": "^5.8.0",
   ```
   in my package.json file and I am unable to use any of the events like ```select``` or ```dateClick```. 
   I am getting this error ```Error: viewType "dayGridMonth" is not available. Please make sure you've loaded all neccessary plugins```
   Additionally, I have these props in the component
   ```
    plugins={[
            interactionPlugin,
            momentPlugin, 
            timeGridPlugin,
            dayGridPlugin, 
          ]}
          initialView='dayGridMonth'
          headerToolbar={headerOptions}
          editable={true}
          selectable={true}
          weekends
          businessHours={true}
          events={events}
          eventClick={handleEventClick}
          ```

**Comment by maximehuran** [comment] 2021-08-12 09:31
@RoniqueRicketts I have the same issue using momentPlugin, timeGridPlugin, dayGridPlugin.
Did you resolve it ?

**Comment by RoniqueRicketts** [comment] 2021-08-12 13:12
@maximehuran I didn't resolve this I ended up using react-big-calendar because I had the stuff to launch. I am enjoying it at the moment.

**Comment by maximehuran** [comment] 2021-08-12 15:18
My issue is with `dayGridPlugin` only.
So I removed it and done my job with the `listPlugin`.

**Comment by tacman** [comment] 2022-04-13 20:08
I'm having the same issue.

```javacsript
CalendarDataManager.prototype._computeCurrentViewData = function (viewType, optionsData, optionOverrides, dynamicOptionOverrides) {
        var viewSpec = optionsData.viewSpecs[viewType];
        if (!viewSpec) {
            throw new Error("viewType \"" + viewType + "\" is not available. Please make sure you've loaded all neccessary plugins");
        }
```

It would be helpful to change this message to list the existing plugins, that is, the keys of optionsData.viewSpecs.  Maybe it has changed names and I'm looking at old documentation, like other I'm not sure what is wrong.
```javascript
        var calendar = new Calendar(calendarEl, {
            // defaultView: 'dayGridMonth', // old version?
            initialView: 'dayGridMonth',
            editable: true,
            eventSources: eventSources,
            headerToolbar: { // was header at one point?
                left: 'prev,next today',
                center: 'title',
                // right: 'month,week,day',
                right: 'dayGridMonth,timeGridWeek,timeGridDay,agendaWeek,agendaDay',
            },
            //  '@fullcalendar/daygrid', '@fullcalendar/list',
            plugins: [listPlugin, timeGridPlugin, dayGridPlugin, interactionPlugin ], // https://fullcalendar.io/docs/plugin-index
            timeZone: 'UTC',
        });
```

Obviously, this code has some of my hacks commented out, seems like I must be missing something obvious

**Comment by arshaw** [comment] 2022-12-09 22:54
As @ashvin777 noted, having all fullcalendar packages at the same version is the solution. This is a current shortcoming with fullcalendar that will be fixed with v6 (in beta):
https://github.com/fullcalendar/fullcalendar/issues/6370
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2022-12-09 22:54 UTC
Labels: Reproducing

**Comment by ngcordovatantrum** [comment] 2025-01-31 02:00
@RoniqueRicketts https://angulardev.space/questions/the-property-dateclick-is-not-found-in-the-calendaroptions-type-in-version-6-of-fullcalendar

**Comment by RoniqueRicketts** [comment] 2025-01-31 03:51
@ngcordovatantrum this is an old issue. I’ve gotten pass this issue ages ago.
