### ISSUE TITLE
"Maximum update depth exceeded" error when updating event state on datesSet with dateIncrement in days

### ISSUE THREAD

**Issue by saramcicchi** [fullcalendar/fullcalendar-react#131] opened 2021-03-09 00:37 UTC
In a custom view, when the ``dateIncrement`` is set to ``{ day: # }`` as opposed to a string ``"hh:mm"``, a "Maximum update depth exceeded" error occurs.

https://codesandbox.io/s/full-calendar-date-increment-bug-yo87v?file=/src/DemoApp.jsx

The above sandbox initially works. But if you comment out the ``dateIncrement: "24:00"`` and uncomment the ``dateIncrement: { days: 1 }``, an error occurs.
![image](https://user-images.githubusercontent.com/5788052/110400204-38dc6a00-8045-11eb-9af6-480a9c904349.png)

**Comment by acerix** [comment] 2021-03-09 18:54
I believe the issue is with updating the event state from dateSet which causes a loop, and likely the same cause as in this issue:
https://github.com/fullcalendar/fullcalendar-react/issues/97

eg. there is no error by commenting out "datesSet":

https://codesandbox.io/s/full-calendar-date-increment-bug-forked-1p5e1?file=/src/DemoApp.jsx

It does seem like a bug and I'm not sure why `dateIncrement` is related, but if you want to supply dynamic events based on dates of the view, you can supply the events "as a function" which is designed for that: 

https://fullcalendar.io/docs/events-function

**Comment by sseemmiin** [comment] 2021-06-16 14:41
same as me on 5.8.0

**Comment by arshaw** [comment] 2022-07-27 03:44
This is been fixed in [v5.11.2](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.11.2)

Updated demo: https://codesandbox.io/s/full-calendar-date-increment-bug-forked-fhxz4q?file=/src/DemoApp.jsx

**Closed by arshaw** 2022-07-27 03:44 UTC
Labels: Confirmed
